hash-format = "sha256"

[[files]]
file = "README.md"
hash = "82c48d692411e08039e242286f40c49f08d62bf544a99093a27261e64edc46bb"

[[files]]
file = "config/DistantHorizons.toml"
hash = "6a1c8a6897eae280ca5ec2bc66ac3e192dcd77900b44d5a002b9218314775177"

[[files]]
file = "config/Mekanism/general.toml"
hash = "afcf1a4deea02567930ce7e560286989deb616f95f14de9feadf3f3fc866d8e3"

[[files]]
file = "config/Mekanism/tiers.toml"
hash = "07d4c457d0ce10cab41820db25c939c9c61446227d40f17cdde02565c5cb2b5d"

[[files]]
file = "config/darkmodeeverywhere-client.toml"
hash = "4fda4b7a5ee3246665c03c8b1492313b074ed2b4d4f5d70891e4ac4763d4a503"

[[files]]
file = "config/effortlessbuilding-common.toml"
hash = "8e6000ef5bfe0b2bb3bde9279c955d59268d34f7b7e2329ab3269637535c1ab4"

[[files]]
file = "config/iris.properties"
hash = "088912d9be27bf197bd0e126731bf42fa03fde2e1d0f938ef707fc0e0069c1ef"

[[files]]
file = "config/sodium-extra-options.json"
hash = "1b36f183cb1364d88ab955f8028f368a70db963a5d2d73bbceaeb37b01b3e601"

[[files]]
file = "config/sodium-options.json"
hash = "73786e9cd2e4013878ba9a595994a8501fd04c416d8323741ed0bace36682218"

[[files]]
file = "kubejs/client_scripts/nukelist.js"
hash = "8008e8c85a4bbe69b7d7d479c87b33177c2d955d0fc5f2eb9cd0fdb817d46994"

[[files]]
file = "kubejs/server_scripts/hostile-neural-networks.js"
hash = "71bc09cb86c5a0e51c48278f74a58eb6b9a24c131fda97d7625291544f524c1b"

[[files]]
file = "kubejs/server_scripts/nukelist.js"
hash = "0a9dbf9be837bfae1c508dccb9823240fa06ab21400aa139256ab33025e0c4aa"

[[files]]
file = "kubejs/startup_scripts/nukelist.js"
hash = "56b6dbca84e0fd441095790f7bf4ce596636e479692482e851cc4850c97d451d"

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "afd9837f16b0b8fe16fe8788470334b7bb13d9c452f46a058d1a2c012f079adf"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "e1599947a8d78f74c129a8420569bb2453b2ce76fdc76a7151093923ea8366c9"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "2bbc57f2edb0c4045b2b46f0126e109d9a8cf72153cd7084cb78f6e3311adb38"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/dark-mode-everywhere.pw.toml"
hash = "d49b12a00673ee8de5b5df8ec5956bf81da551eff4d2a38b230a089b765f2c42"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "3a0da1a01f5281b39b00612f283b405e2d6c64d058cdf0571982a60480afe048"
metafile = true

[[files]]
file = "mods/edivadlib.pw.toml"
hash = "e2271f01117b2e3469832199b0830aacd678be821b4a4121fadd1805e0256195"
metafile = true

[[files]]
file = "mods/effortless-building.pw.toml"
hash = "9eed5211ec173caa872706cd0d1bd0b799826059bb9ba078a52156d78f13e0a3"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "b4085a5772cddefe655155a25d0d24d2f8f34017c61d9cd786d7a9868abf9092"
metafile = true

[[files]]
file = "mods/extra-disks.pw.toml"
hash = "5551e291d2ea656b12d43d354eac2736f7d92242bd548aa4bbf5ae2c475cefef"
metafile = true

[[files]]
file = "mods/extrastorage.pw.toml"
hash = "f0eb56417b0e2594af6bc6edd9bbdaea7038a18040bca259e8ccfa40b2b9d269"
metafile = true

[[files]]
file = "mods/extreme-reactors.pw.toml"
hash = "a3d47e3c301ed2359820c2083dcddec8240a5d692a016c42a74eecc1193772e1"
metafile = true

[[files]]
file = "mods/flat-bedrock.pw.toml"
hash = "d17382ebb5d2d2f7e56e9fbb71b4b9d7ec9a61134dec3de9ef8bfaab876c205a"
metafile = true

[[files]]
file = "mods/forgeendertech.pw.toml"
hash = "5d3594b79a50d63e6966fd45b7ff83b9ee4dbd67d611a276141e96a5feef91ff"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e448ed8448354d972dcd3ef7c46833e58de16147fe947a969538bf80efad6de9"
metafile = true

[[files]]
file = "mods/hostile-neural-networks.pw.toml"
hash = "90f96f9e48eea134f5a399b859d4977d6166a1711c917224375ce832b0b9cf53"
metafile = true

[[files]]
file = "mods/inventory-tweaks-refoxed.pw.toml"
hash = "1d3b922c0d1a43fa497faf27827bfa9f9f3841dfba51d8684435d58c1141fe93"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "89395dd9fcb8ae67889d991207cb95ed7158571c387dde88012853c5fa9ca3fb"
metafile = true

[[files]]
file = "mods/iron-furnaces.pw.toml"
hash = "3f6a27001eb45ce6296829cfa9d7d41a0bd304914217f8dc3196feaa9030f963"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a930b919e6edc62681559da1ebfcdf4873568ad58a0f5d9f73da0093e92ade7b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d068154533d9a999acbb4008f7c33d307b583d2e6db7122a69fc02921ffdb411"
metafile = true

[[files]]
file = "mods/just-enough-mekanism-multiblocks.pw.toml"
hash = "74021b36457eb31ff79c6dd0974b1d624c15fec5416833273b4f7a621946270f"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "f61a3526d323d232fbac74dedb5d89e07f45981db1c5a705c66dbe5da7507a68"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "395ed890024bdb90e7c0fed1edf8b3905a367942ded954fca92384c76a7e5601"
metafile = true

[[files]]
file = "mods/large-ore-deposits.pw.toml"
hash = "ba6cf26620c7308faf9228fd9211bee76533a682c760039c47159f6a799856a7"
metafile = true

[[files]]
file = "mods/mekajadeupgrades.pw.toml"
hash = "198d6aee95af8ed72e535a4f5662e9e9299c182e2c41ffad1e0e4d2c9192fb6f"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "2581c158a3335ec178acac32452224f0b5ae371001d99bd7757827f470abef50"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "a04147d9f39521c236191f913ac7fd8f177cc3ae073d5cb01be52bcede9acab2"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "cf382b0b1ea1f25c133779b6ea340a5953dec3272bfaef17b6b499b4e59cc515"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2fee21be9505fb8a1a199aa5dc7a5d6a0687e86c08951fe396afd5dcfdb0ac45"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "2bdee19bd39b4bd411d7c858a7978ca9d2bdda41c1cf15920ea6be0014663f79"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "9749d73e7add8942aa12ca754ed46d4549f2148bc9f169f4ce94d19f6c5fb4b5"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "f557ccd936f4ea169e747a037bcff023594c343c726722034fa7b57804d3f10d"
metafile = true

[[files]]
file = "mods/ore-excavation.pw.toml"
hash = "8a32a12fac64157e5773f60611f565e1335c4d5b9b5c7f679de5f70dc65e6409"
metafile = true

[[files]]
file = "mods/oritech.pw.toml"
hash = "d67c4d19ce7de51e6748453defe381873b32bae6d8a55dd79804e60e03e63cc9"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3db5943419e6b6f4e33946266be8797230434573bc68dbe3a77d72f19001ae0c"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6a48780ffd4bc3b941f81232c84034aba5ff7645ea635c604de6df71e6596bb3"
metafile = true

[[files]]
file = "mods/refined-storage-jei-integration.pw.toml"
hash = "4ef51a87a42bf93295c8af21e543d41b204a7b604a810a2329923937362d2e61"
metafile = true

[[files]]
file = "mods/refined-storage-mekanism-integration.pw.toml"
hash = "a0572398bbce4b3bc0671939e57c3cc67c2dfb831aa42dadfa2c8438e9183044"
metafile = true

[[files]]
file = "mods/refined-storage-quartz-arsenal.pw.toml"
hash = "a919e9f1bbbe6d68c5115f9dd60606d49d86ab0985d3cb7789d26220814896b6"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "8379747fafa54270c5565e0e243ca14e0f9ad1a6636fde0abac7db8a9d0deca1"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "75ff68dd0bfb30f2ff97f170ffbb74d5b6aaa791416c4a0559d09ac8778561ba"
metafile = true

[[files]]
file = "mods/rs-requestify.pw.toml"
hash = "90df3fe04baefe2064d72661d9cb915b730ab918afbaa2e60d0a1363d43c2553"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/simple-backups.pw.toml"
hash = "23d873430afcc70fb541313d4db2572df19839cafeb1b2e000ee4c7d9376d549"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "f0921e672c9519eff90da52406b64f84661604f067fc7bd3361f1906b2788344"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "36bc1bb632d1203c91d99298214b08b6babc7da301fff00fded2a1f705592f17"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "9f0cd1d096b591cb49077fbe4f95a1e24a93354cd9b4d77e74c49af2d29381cf"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "0e02e93b9468dca005f7fea385e92612e38bb6807f4dcd64ce7a4b22fac78581"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "de4e42a8d1496f13ddd6c54f291e87e0e802c0deb08ef37daf8d2887c8657ee3"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "492daa3391b6079b541685db276007b286774bab3b9881505127b7aef6b3f16c"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
hash = "7c6f2e38a6932f846738747fd6cff3af239748a84e89350f6c967c8ac72a65d6"
metafile = true

[[files]]
file = "mods/zerocore.pw.toml"
hash = "f60046584d023aaa0af0e8a1f3f021acb13121f2130f7c66b85e704da4d72643"
metafile = true

[[files]]
file = "options.txt"
hash = "e43aeb7053f986d5c16cf9e14deca4bb14a231960a0f15d49a2bbe62928e3478"

[[files]]
file = "resourcepacks/JetBrainsMonoFont/assets/minecraft/font/default.json"
hash = "4410582a63a818cf40dbf02c80e3cf0764431b2a183a16d24e1cd7afad14905f"

[[files]]
file = "resourcepacks/JetBrainsMonoFont/assets/minecraft/font/jetbrains-mono.ttf"
hash = "192a3158a926768d1fa520164f0fb0f40a6ad085435aa854e43eb14cb40d1aab"

[[files]]
file = "resourcepacks/JetBrainsMonoFont/pack.mcmeta"
hash = "45813f826017536654c3998d154973985c11e5b73183e1b18f71eaef9829639f"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "9f8e443df6075210eef82f35c5f95db92c19d7b1a1267a4593fa97c079993ed6"
metafile = true
