hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "6a1c8a6897eae280ca5ec2bc66ac3e192dcd77900b44d5a002b9218314775177"

[[files]]
file = "config/Mekanism/general.toml"
hash = "afcf1a4deea02567930ce7e560286989deb616f95f14de9feadf3f3fc866d8e3"

[[files]]
file = "config/Mekanism/tiers.toml"
hash = "8e0ecf1d23ee43f1b3ff255d6cc0ba7d494432de2aa03123fc42d0d17c35bffd"

[[files]]
file = "config/darkmodeeverywhere-client.toml"
hash = "4fda4b7a5ee3246665c03c8b1492313b074ed2b4d4f5d70891e4ac4763d4a503"

[[files]]
file = "config/effortlessbuilding-common.toml"
hash = "8e6000ef5bfe0b2bb3bde9279c955d59268d34f7b7e2329ab3269637535c1ab4"

[[files]]
file = "config/iris.properties"
hash = "088912d9be27bf197bd0e126731bf42fa03fde2e1d0f938ef707fc0e0069c1ef"

[[files]]
file = "config/jamd/end.json"
hash = "9e1ddd94a40ba0d3fb99d148dd21a0a94afe78f07ec39d831e2b7e0e472edb8a"

[[files]]
file = "config/jamd/mining.json"
hash = "63d6c26c5077c6d88c1800ed22203823d6368f580d7557eb5d7d4b650ebd79b3"

[[files]]
file = "config/jamd/nether.json"
hash = "631ddf19bd04531a3f1f553e5de02d523293f95fd19f0aabedeb462e024de0f2"

[[files]]
file = "config/oritech-config.json5"
hash = "2b5dd03f72cf29e12a6468ffae94e38a13abf59bc22b5c21532ba4bbdebd087e"

[[files]]
file = "config/sodium-extra-options.json"
hash = "e4a2484527d399216407d56923b4e9aaae4521a2666bf00f82d437aadce79913"

[[files]]
file = "config/sodium-options.json"
hash = "73786e9cd2e4013878ba9a595994a8501fd04c416d8323741ed0bace36682218"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "3dc162923132417a309be76de95ba395a8268612eea2c50767dbd84b185e2d6c"

[[files]]
file = "kubejs/client_scripts/nukelist.js"
hash = "8008e8c85a4bbe69b7d7d479c87b33177c2d955d0fc5f2eb9cd0fdb817d46994"

[[files]]
file = "kubejs/data/bigreactors/worldgen/placed_feature/yellorite_deepslate_ore.json"
hash = "9b410a7e65bbaa1927ffbb85bb22c61aa1d7473e2abdccdc8e910e7f207a716a"

[[files]]
file = "kubejs/data/bigreactors/worldgen/placed_feature/yellorite_ore.json"
hash = "5511e6087f92b236ccabb9f74117fc414716225061f06e235fe6b0d91e37ea2b"

[[files]]
file = "kubejs/server_scripts/ender-storage/recipies.js"
hash = "4763084a05acd4374cab000be1df5f790113ff2547e7eaae1a8f0dd2ac6ba56f"

[[files]]
file = "kubejs/server_scripts/hostile-neural-networks.js"
hash = "97a047fed1a3ea36df98a0da1ca8a0ff9fce1c0ceffd2b62adae1ec078856dc9"

[[files]]
file = "kubejs/server_scripts/mekanism/recipies.js"
hash = "83b51b0f7a6c0c2b3cb31b64dd8ce22e6703eeb29f0395139360e2d6b8f9596e"

[[files]]
file = "kubejs/server_scripts/nukelist.js"
hash = "0a9dbf9be837bfae1c508dccb9823240fa06ab21400aa139256ab33025e0c4aa"

[[files]]
file = "kubejs/server_scripts/remove-crafting-recipies.js"
hash = "9b6d99c81697c8a199d5739ee7c57d68d932d1c2a396d1a4e193fa9c9761d2ca"

[[files]]
file = "kubejs/server_scripts/rftools-builder/recipies.js"
hash = "480ea8e9d76246170a15323d0f21332ef47f12ff45209eefa10d1a83f577f697"

[[files]]
file = "kubejs/startup_scripts/nukelist.js"
hash = "95958e25a9e90054d8bb1289c348fb04f03447ec5cb21870a104239f896bffe9"

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "afd9837f16b0b8fe16fe8788470334b7bb13d9c452f46a058d1a2c012f079adf"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "e1599947a8d78f74c129a8420569bb2453b2ce76fdc76a7151093923ea8366c9"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "2bbc57f2edb0c4045b2b46f0126e109d9a8cf72153cd7084cb78f6e3311adb38"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/dark-mode-everywhere.pw.toml"
hash = "d49b12a00673ee8de5b5df8ec5956bf81da551eff4d2a38b230a089b765f2c42"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "3a0da1a01f5281b39b00612f283b405e2d6c64d058cdf0571982a60480afe048"
metafile = true

[[files]]
file = "mods/edivadlib.pw.toml"
hash = "e2271f01117b2e3469832199b0830aacd678be821b4a4121fadd1805e0256195"
metafile = true

[[files]]
file = "mods/effortless-building.pw.toml"
hash = "9eed5211ec173caa872706cd0d1bd0b799826059bb9ba078a52156d78f13e0a3"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "b4085a5772cddefe655155a25d0d24d2f8f34017c61d9cd786d7a9868abf9092"
metafile = true

[[files]]
file = "mods/extra-disks.pw.toml"
hash = "5551e291d2ea656b12d43d354eac2736f7d92242bd548aa4bbf5ae2c475cefef"
metafile = true

[[files]]
file = "mods/extrastorage.pw.toml"
hash = "f0eb56417b0e2594af6bc6edd9bbdaea7038a18040bca259e8ccfa40b2b9d269"
metafile = true

[[files]]
file = "mods/extreme-reactors.pw.toml"
hash = "a3d47e3c301ed2359820c2083dcddec8240a5d692a016c42a74eecc1193772e1"
metafile = true

[[files]]
file = "mods/flat-bedrock.pw.toml"
hash = "d17382ebb5d2d2f7e56e9fbb71b4b9d7ec9a61134dec3de9ef8bfaab876c205a"
metafile = true

[[files]]
file = "mods/forgeendertech.pw.toml"
hash = "5d3594b79a50d63e6966fd45b7ff83b9ee4dbd67d611a276141e96a5feef91ff"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "6a2693aaab21ce7c32b958b81ee5e9cad0d014cdf68c067049b2fc652159d9d1"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e448ed8448354d972dcd3ef7c46833e58de16147fe947a969538bf80efad6de9"
metafile = true

[[files]]
file = "mods/hostile-neural-networks.pw.toml"
hash = "90f96f9e48eea134f5a399b859d4977d6166a1711c917224375ce832b0b9cf53"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "dbc34ada7af1fe08105d440312f544dc1fc0ef2032ef8bc0adda9f0e9c4fb067"
metafile = true

[[files]]
file = "mods/inventory-tweaks-refoxed.pw.toml"
hash = "1d3b922c0d1a43fa497faf27827bfa9f9f3841dfba51d8684435d58c1141fe93"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "89395dd9fcb8ae67889d991207cb95ed7158571c387dde88012853c5fa9ca3fb"
metafile = true

[[files]]
file = "mods/iron-furnaces.pw.toml"
hash = "3f6a27001eb45ce6296829cfa9d7d41a0bd304914217f8dc3196feaa9030f963"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e739b7355ab3cfba2e729f8f0b51eafc3d9c3afb19ee30ac7b311631610c5e66"
metafile = true

[[files]]
file = "mods/jamd.pw.toml"
hash = "d79e4f41f50658be56d750bc32f3be1033c35cd9597bc599c89bc3fda7a54e82"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d068154533d9a999acbb4008f7c33d307b583d2e6db7122a69fc02921ffdb411"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "729cdb84e286f2444198847eb475f3b2d0190aff3cb8c7726497d88577135365"
metafile = true

[[files]]
file = "mods/just-enough-mekanism-multiblocks.pw.toml"
hash = "74021b36457eb31ff79c6dd0974b1d624c15fec5416833273b4f7a621946270f"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "f61a3526d323d232fbac74dedb5d89e07f45981db1c5a705c66dbe5da7507a68"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "5345bb641d6b9307c6a05f12885315537386519476bd2aee79d9fd1181268a7a"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "e8ad4c0b1a01858f6d653672472641f24aeacf7d6fb3b63a4358157312381a76"
metafile = true

[[files]]
file = "mods/kubejs-mekanism.pw.toml"
hash = "d8e177615c38e56e8f712f9144c0f9f50e74adf5fe88c7fb0aa88e33cb1dbcdc"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "395ed890024bdb90e7c0fed1edf8b3905a367942ded954fca92384c76a7e5601"
metafile = true

[[files]]
file = "mods/large-ore-deposits.pw.toml"
hash = "ba6cf26620c7308faf9228fd9211bee76533a682c760039c47159f6a799856a7"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "90884d8e75897120ad7e7a6fc4ad3ab2a08bcf050286a98cac27c7412e043a68"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "92f8cdfdc3e3f14a3cb6b35b639c955c87bed7d3089485e4e2a40fb50f70c94b"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
hash = "b9a0690a13cd849af6fe942cf34e5c44c4e5ac53c5f0b3bc986070ecb7f266b3"
metafile = true

[[files]]
file = "mods/mekajadeupgrades.pw.toml"
hash = "20ba1021bb3047a3c56ffa39b40c97638211934b3fb129b9ee9b66e99387822d"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "2581c158a3335ec178acac32452224f0b5ae371001d99bd7757827f470abef50"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "a04147d9f39521c236191f913ac7fd8f177cc3ae073d5cb01be52bcede9acab2"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "cf382b0b1ea1f25c133779b6ea340a5953dec3272bfaef17b6b499b4e59cc515"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2fee21be9505fb8a1a199aa5dc7a5d6a0687e86c08951fe396afd5dcfdb0ac45"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "2bdee19bd39b4bd411d7c858a7978ca9d2bdda41c1cf15920ea6be0014663f79"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "9749d73e7add8942aa12ca754ed46d4549f2148bc9f169f4ce94d19f6c5fb4b5"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "f557ccd936f4ea169e747a037bcff023594c343c726722034fa7b57804d3f10d"
metafile = true

[[files]]
file = "mods/ore-excavation.pw.toml"
hash = "8a32a12fac64157e5773f60611f565e1335c4d5b9b5c7f679de5f70dc65e6409"
metafile = true

[[files]]
file = "mods/oritech.pw.toml"
hash = "0727c080dffa11ec3a6bb06cd49f1e00f76793e0739da0c8203150039b9f056d"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3db5943419e6b6f4e33946266be8797230434573bc68dbe3a77d72f19001ae0c"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "5328219480c6d7aa255c6288f2839b683ffc1bcc52449383244cd11cfbf85f83"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6a48780ffd4bc3b941f81232c84034aba5ff7645ea635c604de6df71e6596bb3"
metafile = true

[[files]]
file = "mods/refined-storage-jei-integration.pw.toml"
hash = "4ef51a87a42bf93295c8af21e543d41b204a7b604a810a2329923937362d2e61"
metafile = true

[[files]]
file = "mods/refined-storage-mekanism-integration.pw.toml"
hash = "a0572398bbce4b3bc0671939e57c3cc67c2dfb831aa42dadfa2c8438e9183044"
metafile = true

[[files]]
file = "mods/refined-storage-quartz-arsenal.pw.toml"
hash = "a919e9f1bbbe6d68c5115f9dd60606d49d86ab0985d3cb7789d26220814896b6"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "8379747fafa54270c5565e0e243ca14e0f9ad1a6636fde0abac7db8a9d0deca1"
metafile = true

[[files]]
file = "mods/rftools-base.pw.toml"
hash = "71f638c4d9efeaca22061f5e5690e40710284928b836ec936ba8a375afa8dff1"
metafile = true

[[files]]
file = "mods/rftools-builder.pw.toml"
hash = "ab4897860cab54da7523478c82681686f09312171f84554b446ffea0ccc53a96"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "75ff68dd0bfb30f2ff97f170ffbb74d5b6aaa791416c4a0559d09ac8778561ba"
metafile = true

[[files]]
file = "mods/rs-requestify.pw.toml"
hash = "90df3fe04baefe2064d72661d9cb915b730ab918afbaa2e60d0a1363d43c2553"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/simple-backups.pw.toml"
hash = "23d873430afcc70fb541313d4db2572df19839cafeb1b2e000ee4c7d9376d549"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "f0921e672c9519eff90da52406b64f84661604f067fc7bd3361f1906b2788344"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "36bc1bb632d1203c91d99298214b08b6babc7da301fff00fded2a1f705592f17"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "9f0cd1d096b591cb49077fbe4f95a1e24a93354cd9b4d77e74c49af2d29381cf"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "f1b4f0080de1ab714d033e2f9c492073cc1f41de3c44337a1407dbb81b0e5054"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "0e02e93b9468dca005f7fea385e92612e38bb6807f4dcd64ce7a4b22fac78581"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "de4e42a8d1496f13ddd6c54f291e87e0e802c0deb08ef37daf8d2887c8657ee3"
metafile = true

[[files]]
file = "mods/trenzalore.pw.toml"
hash = "97b31515b4ea9f529c8d41770bc4e584321929b014bd5ab460905114de17492b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "492daa3391b6079b541685db276007b286774bab3b9881505127b7aef6b3f16c"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
hash = "7c6f2e38a6932f846738747fd6cff3af239748a84e89350f6c967c8ac72a65d6"
metafile = true

[[files]]
file = "mods/zerocore.pw.toml"
hash = "f60046584d023aaa0af0e8a1f3f021acb13121f2130f7c66b85e704da4d72643"
metafile = true

[[files]]
file = "options.txt"
hash = "b8ddd777c9657155c46911e0bd8392a6d102b1cee2ebc35bfe2a4e1989ce1af5"

[[files]]
file = "resourcepacks/JetBrainsMonoFont/assets/minecraft/font/default.json"
hash = "4410582a63a818cf40dbf02c80e3cf0764431b2a183a16d24e1cd7afad14905f"

[[files]]
file = "resourcepacks/JetBrainsMonoFont/assets/minecraft/font/jetbrains-mono.ttf"
hash = "192a3158a926768d1fa520164f0fb0f40a6ad085435aa854e43eb14cb40d1aab"

[[files]]
file = "resourcepacks/JetBrainsMonoFont/pack.mcmeta"
hash = "45813f826017536654c3998d154973985c11e5b73183e1b18f71eaef9829639f"

[[files]]
file = "resourcepacks/fusion-connected-blocks.pw.toml"
hash = "b5395a87ff650ccd9253568779f85deebf8186645219d4c6461f78645f03f0bd"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-glass.pw.toml"
hash = "9558758e85c4d4e25da6c62d2381e24de2794f1307136ee9b4be98ed32baf6ad"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "753adc976b00bdb2f4e060e18700d778d0938c76805c46747acccb139fdc7025"
metafile = true
