hash-format = "sha256"

[[files]]
file = "README.md"
hash = "8f204a5e3f15ec92e9e56cd0e741e89baa41e97cb1c8cf7883b56347cadcb6c8"

[[files]]
file = "config/Mekanism/general.toml"
hash = "6a49a2810766c272012bf72aa298364b09a963d3d613515f3a591f3d103ed95d"

[[files]]
file = "config/Mekanism/tiers.toml"
hash = "07d4c457d0ce10cab41820db25c939c9c61446227d40f17cdde02565c5cb2b5d"

[[files]]
file = "config/solarflux/panels.cfg"
hash = "a6a740b87850a68a8c856c7d0dc8924bb21309059759d63b00de9ef4e709f271"

[[files]]
file = "kubejs/server_scripts/hostile-neural-networks.js"
hash = "71bc09cb86c5a0e51c48278f74a58eb6b9a24c131fda97d7625291544f524c1b"

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "afd9837f16b0b8fe16fe8788470334b7bb13d9c452f46a058d1a2c012f079adf"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "2bbc57f2edb0c4045b2b46f0126e109d9a8cf72153cd7084cb78f6e3311adb38"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/cucumber.pw.toml"
hash = "1cb2c004ea6d9750b2c9f399ddb58be0335adc710e63b9cdae5d620ad86dbd5b"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "3a0da1a01f5281b39b00612f283b405e2d6c64d058cdf0571982a60480afe048"
metafile = true

[[files]]
file = "mods/edivadlib.pw.toml"
hash = "e2271f01117b2e3469832199b0830aacd678be821b4a4121fadd1805e0256195"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "b4085a5772cddefe655155a25d0d24d2f8f34017c61d9cd786d7a9868abf9092"
metafile = true

[[files]]
file = "mods/extra-disks.pw.toml"
hash = "5551e291d2ea656b12d43d354eac2736f7d92242bd548aa4bbf5ae2c475cefef"
metafile = true

[[files]]
file = "mods/extrastorage.pw.toml"
hash = "f0eb56417b0e2594af6bc6edd9bbdaea7038a18040bca259e8ccfa40b2b9d269"
metafile = true

[[files]]
file = "mods/extreme-reactors.pw.toml"
hash = "a3d47e3c301ed2359820c2083dcddec8240a5d692a016c42a74eecc1193772e1"
metafile = true

[[files]]
file = "mods/hammer-lib.pw.toml"
hash = "9b8962702b35ed62501aa63a45319f93a8eb06fc05469a1e72c7db3c7dd0e452"
metafile = true

[[files]]
file = "mods/hostile-neural-networks.pw.toml"
hash = "90f96f9e48eea134f5a399b859d4977d6166a1711c917224375ce832b0b9cf53"
metafile = true

[[files]]
file = "mods/inventory-tweaks-refoxed.pw.toml"
hash = "1d3b922c0d1a43fa497faf27827bfa9f9f3841dfba51d8684435d58c1141fe93"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "89395dd9fcb8ae67889d991207cb95ed7158571c387dde88012853c5fa9ca3fb"
metafile = true

[[files]]
file = "mods/iron-furnaces.pw.toml"
hash = "3f6a27001eb45ce6296829cfa9d7d41a0bd304914217f8dc3196feaa9030f963"
metafile = true

[[files]]
file = "mods/iron-jetpacks.pw.toml"
hash = "396254c3cd156fa0bfd06d1fef4af115c21e7222e3c2fa13450e89f50bc7df40"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a930b919e6edc62681559da1ebfcdf4873568ad58a0f5d9f73da0093e92ade7b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d068154533d9a999acbb4008f7c33d307b583d2e6db7122a69fc02921ffdb411"
metafile = true

[[files]]
file = "mods/just-enough-mekanism-multiblocks.pw.toml"
hash = "74021b36457eb31ff79c6dd0974b1d624c15fec5416833273b4f7a621946270f"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "f61a3526d323d232fbac74dedb5d89e07f45981db1c5a705c66dbe5da7507a68"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "395ed890024bdb90e7c0fed1edf8b3905a367942ded954fca92384c76a7e5601"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
hash = "b9a0690a13cd849af6fe942cf34e5c44c4e5ac53c5f0b3bc986070ecb7f266b3"
metafile = true

[[files]]
file = "mods/mekajadeupgrades.pw.toml"
hash = "52705a11a847b42a34892a5978713db458d73c1368a5ffbedc4dfdc68c56a75b"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "2581c158a3335ec178acac32452224f0b5ae371001d99bd7757827f470abef50"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "a04147d9f39521c236191f913ac7fd8f177cc3ae073d5cb01be52bcede9acab2"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "cf382b0b1ea1f25c133779b6ea340a5953dec3272bfaef17b6b499b4e59cc515"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2fee21be9505fb8a1a199aa5dc7a5d6a0687e86c08951fe396afd5dcfdb0ac45"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "2bdee19bd39b4bd411d7c858a7978ca9d2bdda41c1cf15920ea6be0014663f79"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "f557ccd936f4ea169e747a037bcff023594c343c726722034fa7b57804d3f10d"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6a48780ffd4bc3b941f81232c84034aba5ff7645ea635c604de6df71e6596bb3"
metafile = true

[[files]]
file = "mods/refined-storage-jei-integration.pw.toml"
hash = "4ef51a87a42bf93295c8af21e543d41b204a7b604a810a2329923937362d2e61"
metafile = true

[[files]]
file = "mods/refined-storage-mekanism-integration.pw.toml"
hash = "a0572398bbce4b3bc0671939e57c3cc67c2dfb831aa42dadfa2c8438e9183044"
metafile = true

[[files]]
file = "mods/refined-storage-quartz-arsenal.pw.toml"
hash = "a919e9f1bbbe6d68c5115f9dd60606d49d86ab0985d3cb7789d26220814896b6"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "8379747fafa54270c5565e0e243ca14e0f9ad1a6636fde0abac7db8a9d0deca1"
metafile = true

[[files]]
file = "mods/rftools-base.pw.toml"
hash = "71f638c4d9efeaca22061f5e5690e40710284928b836ec936ba8a375afa8dff1"
metafile = true

[[files]]
file = "mods/rftools-builder.pw.toml"
hash = "ab4897860cab54da7523478c82681686f09312171f84554b446ffea0ccc53a96"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "75ff68dd0bfb30f2ff97f170ffbb74d5b6aaa791416c4a0559d09ac8778561ba"
metafile = true

[[files]]
file = "mods/rs-requestify.pw.toml"
hash = "90df3fe04baefe2064d72661d9cb915b730ab918afbaa2e60d0a1363d43c2553"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/solar-flux-reborn.pw.toml"
hash = "00b5410e4e61d67f4c6b67a6eeb1f3da5092d6775c0b3d26b321d7d8ecee65db"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "9f0cd1d096b591cb49077fbe4f95a1e24a93354cd9b4d77e74c49af2d29381cf"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "de4e42a8d1496f13ddd6c54f291e87e0e802c0deb08ef37daf8d2887c8657ee3"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
hash = "7c6f2e38a6932f846738747fd6cff3af239748a84e89350f6c967c8ac72a65d6"
metafile = true

[[files]]
file = "mods/zerocore.pw.toml"
hash = "f60046584d023aaa0af0e8a1f3f021acb13121f2130f7c66b85e704da4d72643"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "9f8e443df6075210eef82f35c5f95db92c19d7b1a1267a4593fa97c079993ed6"
metafile = true
