hash-format = "sha256"

[[files]]
file = "config/Mekanism/tiers.toml"
hash = "07d4c457d0ce10cab41820db25c939c9c61446227d40f17cdde02565c5cb2b5d"

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "3a0da1a01f5281b39b00612f283b405e2d6c64d058cdf0571982a60480afe048"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d068154533d9a999acbb4008f7c33d307b583d2e6db7122a69fc02921ffdb411"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2fee21be9505fb8a1a199aa5dc7a5d6a0687e86c08951fe396afd5dcfdb0ac45"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "9f8e443df6075210eef82f35c5f95db92c19d7b1a1267a4593fa97c079993ed6"
metafile = true
