name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d4e59f98328c83be436d9be5dbe97dc676aca66af1d1169ff6b4f7e4b38a950"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
