name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd8e7a1cfd9a03d9ccdd359889715f73086f3d320ad4abb1ba41b19594b9c05b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
