name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2afc3c0c70099221afe66c0878808be5cf624a7c1e559cd9543cbad0e657d140"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
