name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce177f1ee5cd109d813a9973ab30e7876e3c099e48eef391352a62146cc279f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
