name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4ec2c8efbdb7ff972ed4a30c0a86124b0147650befed2142a6b4b688c5b1d16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
