name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9169f2a83c8e3c53359794943b39b67efc0289689f9017edf5a2745e9572f344"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
