name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4995e17a8edd558ae946ba96ec599f8bb424af5ffbf041ed512e29cf900f330e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
