name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3eadbe1de2eeabac928fbacf86219c941d4b7d19f868ecbb3b5551d0b6b784a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
