name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe62f2388d702e1576dc06e907e89da5de7b005ce05bf05411073832c8d68d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
