name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4878d759a82992204676aa3cefd2fbb58b036e8c8208fdc9d6dc9964b32489da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
