name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f947f59996ef52e60dd2086962530bac8b2b115281ee02281e535e3dd3bb209"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
