name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "667b1c9db810de51b7df64b7ff5f26e52f4a94277e6d90f6996f2cc88b236cef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
