name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de7062a54cc0656141af88cfe618a03cb9d536376c0350cd24ebb19a7a9e6623"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
