name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebc53f9047d5050be1c03f5a0ee2b26c6a1fe0478cfb30c0fcbcc822da9b68b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
