name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960c1ceb250b4eea122aeef60292cabcdc42b2b6b69045c13d2b21a8d537a4a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
