name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee701e8a9912228c779fa807c174a7a39aeeb67ae6153357bcc2f42d26da755e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
