name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a855176ff452bee1696ade3a0f6e4e7cfb7d8a1f441951ab467d5b048993c45b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
