name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d33fbe3da0c0081b5be3b2dba86c981a582f7931dadafb00234c713437783a9c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
