name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63ce034188f9a6731405ccf3e856c4537c755e50ed461146fe18270df9701935"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
