name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4432b342d3ba93d34e5fa22f34de4e58cb27e8615968294a62ae0ec52f3c2ec2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
