name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0df2e2308b1ae2817ebe03126883fc6ec33620377e6197a2cfdcab23a7e10881"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
