name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f46c07df7ad2b77d6e8f2f9ec8d17033a420a62cb3c4ee16f774ad635748b91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
