name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f032d27ce63749d5f0785453b4df4de5ade01e91ca1f659c23c093aefb12aad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
