name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42de2c46c0f160fffefc4e9eee0277a167f42d31f61e0a1f53cac190178660c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
