name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bce116ef6644248595866b76a2ecbcc5abfe7efe6a1ec1c875e9bf64936539fc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
