name = "Dantech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6f5698dff5777e032c237ce6d95f01871f14ab4c57e8fc0b7688467c046af30"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
