name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export Modpacks
        run: |
          REPO_NAME: ${{ github.event.repository.name }}
          TAG_NAME=${{ github.ref_name }}
          packwiz curseforge export --output "${REPO_NAME}-curseforge-${TAG_NAME}.zip"
          packwiz modrinth export --output "${REPO_NAME}-modrinth-${TAG_NAME}.mrpack"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          append_body: false
          files: |
            ${{ github.event.repository.name }}-curseforge-${{ github.ref_name }}.zip
            ${{ github.event.repository.name }}-modrinth-${{ github.ref_name }}.mrpack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}